sudo: false
language:
  - node_js
node_js:
  - "0.10"
  - iojs-1.0
before_script: bin/.travis-ldf
script: bin/test
cache:
  directories:
  - node_modules

notifications:
  irc: chat.freenode.net##senet
  email: false
