
sudo: false
language:
  - node_js
node_js: "0.10"
install:
  - "npm install"
script: bin/test
cache:
  directories:
  - node_modules

notifications:
  irc: "chat.freenode.net##senet"
  email: false

